apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memory-box-front
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: public
  tls:
    - hosts:
        - innovbi.site
        - www.innovbi.site
      secretName: memory-box-front-tls
  rules:
    - host: innovbi.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memory-box-front
                port:
                  number: 80
    - host: www.innovbi.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memory-box-front
                port:
                  number: 80
